steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/explorecali-fe','.']

  # Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/explorecali-fe:latest']

options:
  logging: CLOUD_LOGGING_ONLY

images: ['gcr.io/$PROJECT_ID/explorecali-fe']


