apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorecali-fe-app
  name: explorecali-fe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: explorecali-fe-app
  template:
    metadata:
      labels:
        app: explorecali-fe-app
    spec:
      containers:
        - image: gcr.io/explorecalicicd/explorecali-fe:latest
          name: explorecali-fe-app
          ports:
            - containerPort: 4200

---
apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: explorecali-fe-app
spec:
  selector:
    # Selector for Pods
    app: explorecali-fe-app
  ports:
    # Port Map
    - port: 80
      targetPort: 4200
      protocol: TCP
  type: LoadBalancer

